name: Profiles
version: 1.3.3
main: com.cmpscjg.profiles.Profiles
api-version: 1.16
authors: [ CMPSCjg ]
description: Bukkit/Spigot plugin that allows players to save progress to profiles.
website: https://github.com/CMPSCjg
commands:
  profiles:
    description: Main plugin command
    usage: /<command>


permissions:
  profiles.*:
    description: Gives access to all Profiles features/commands.
    children:
      profiles.reload: true
  profiles.reload:
    description: Allows you to reload plugin configuration.
    default: op